### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by mattheu** [humanmade/hm-pattern-library#127]
Some of our existing icons don't fit so well with the new design. Plus I think we need a download icon. Showing a screenshot of icons below.

These are the ones I think we need:
- Loading spinner. Up to you what this looks like, but the current arrow is slightly different from the right arrow you used. Also we only need one style for this rather than the 2 that we have currently.
- Plus & Minus - These are actually used for expand/collapse in the nav, so if you think a different icon would work here, thats cool eg a 
- Left arrow version of the right arrow.

Plus any others you think could be improved. 

![image](https://cloud.githubusercontent.com/assets/494927/26347418/6d51893e-3fa1-11e7-9977-aae7a678115a.png)

**Comment by grarighe** [comment]
@mattheu I created this: https://drive.google.com/open?id=0B21-BcVlg9MVQ0U2YkRyNHgxR1U

I changed the "link" arrow a bit (it was too rounded and didn't match the other icons) but the two arrows are still different (and that's because the rotating arrow doesn't look great with the other style), tbh it doesn't bother me too much but we can change that to be a nice animation on the button (https://tympanus.net/Development/ProgressButtonStyles/) or 3 lovely jumping dots. :)

**Comment by mattheu** [comment]
Thanks so much for this. These are looking really nice!

![image](https://cloud.githubusercontent.com/assets/494927/26448667/495a704e-4146-11e7-8e7b-0127524ca9f3.png)

Just to confirm with the left/right arrows. Personally I think I like the versions in use on the hmn.md site right now so have stuck with that and would rather keep to a single variation in the pattern library. I don't think it matters they don't perfectly match the spinner icon.

One other icon that I think I have seen in your designs is the download icon. Do you have the svg for this available?

**Comment by mattheu** [comment]
Closing this one for now. We can open individual tickets for icons.
